---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=12mm
      - left=16mm
      - right=16mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{center}
{\fontsize{40}{60}\selectfont \textbf{Addison Pratt}}
\end{center}

<!-- CONTACT INFO -->
\begin{center} 208.872.5895 | prattjds@gmail.com | linkedin.com/in/addisonpratt
\end{center}
\vspace{12pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Brigham Young University- Idaho}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}B.Sc. Data Science, Statistics; \textit{GPA: 4.0} \end{flushleft}
    \begin{flushright}Jan 2022 - Apr 2025\end{flushright}
  \end{multicols}
  \vspace{-0.25cm}
\end{large}

\vspace{0.2cm}


\vspace{7pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
\vspace{3pt}
\hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf WPA Intelligence}\end{flushleft}
    \begin{flushright}Washington D.C.\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Science Intern}\end{flushleft}
    \begin{flushright}May 2023 - Sept 2023\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

* Designed and Implemented advanced machine learning models to predict voter behaviors, achieving an accuracy rate of over 90%, aiding in the formulation of targeted campaign strategies.
* Innovated an advanced R script to automate report generation from a SQL database, eliminating manual data entry and significantly boosting departmental productivity.
* Collaborated on a cross-functional team initiative, deriving actionable insights on voter behavior to influence targeted political campaign strategies.
* Achieved high data reliability by executing a comprehensive webscraping strategy, collecting political data from 16 states and over 8,500 articles.
* Enhanced data quality by cleaning and standardizing over 100,000 rows of raw data, optimizing targeted campaigning efforts and improving overall data accuracy.

\vspace{7pt}
<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Ohio Elect Political Consulting}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Founder, Data Scientist}\end{flushleft}
    \begin{flushright}Sept 2023 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Spearheaded data-driven methodologies to empower grassroots campaigns in Ohio, orchestrating over 8 million rows of data to unveil pivotal political narratives and foster community engagement.
* Leveraged machine learning models to predict party affiliation in the 2024 General Election and the probability of voter turnout, resulting in cost-effective campaigning and saving substantial hours in campaign efforts.
* Directed campaign strategies leveraging data insights, optimizing resource allocation and engagement approaches.
* Strategizing to broaden the impact of the established data processing infrastructure across various campaigns nationwide.
* Awarded 1st Place in the 2023 I-Hack Hackathon for showcasing innovative data analysis techniques and solutions.

<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Mathematics Department BYU-Idaho}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Science Tutor}\end{flushleft}
    \begin{flushright}Sept 2023 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Tutored students seeking help in programming and mathematics for all intermediate level data science courses using various data science and machine learning libraries within Python and R including Pandas, Tidyverse, ggplot2, Numpy, Sklearn, and TensorFlow

\vspace{6pt}

\begin{large}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Teacher's Assistant}\end{flushleft}
    \begin{flushright}Apr 2022 - Dec 2022\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* **Biostatistics**: Tutored basic statistical analyses, theories, and methods with Excel.
* **Applied Math with Excel**: Tutored students to identify real-world situations (e.g. financial, family, social, or community issues) where quantitative reasoning skills are needed to inform a decision.

\vspace{6pt}

\begin{large}{\bf PROJECTS}
\hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Heart Failure Assessment Tool}\end{flushleft}
    \begin{flushright}Rexburg, ID\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Scientist}\end
    {flushleft}\begin{flushright}Feb 2023\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Constructed a random forest model utilizing data from 3,000 patients, attaining an 85% accuracy rate in forecasting heart failure survival outcomes.
* Designed an interactive cloud app, enabling real-time predictions and enhancing user experience.
* Leveraged the model to identify critical patterns and connections, offering valuable insights that may be overlooked by medical professionals.

\vspace{6pt}

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
\vspace{6pt}
* **Python**: Pandas, NumPy, Sci-kit Learn, PySpark, Polars, Keras / Tensorflow, BeautifulSoup4, DataBricks
\vspace{2pt}
* **R**: Mosaic, RMarkdown, Tidyverse (dplyr, tidyr, stringr, tidymodels, lubridate, purrr, etc.) 
\vspace{2pt}
* **Visualization Libraries**: Tableau, ggplot2, Matplotlib / Seaborn, Plotly Express, Altair
\vspace{2pt}
* **Other Technical Skills**: SQL, C#, ArcGIS, Microsoft Office, Git/GitHub, Statistical Analysis, Data Wrangling
\vspace{2pt}


